
[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-immutable-radix"

[[constraint]]
  name = "github.com/willf/bitset"
  version = "^1.1.3"

[[constraint]]
  branch = "master"
  name = "github.com/martingallagher/runes"
